name: Build Magisk Module

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Magisk Module
        run: |
          # Remove files that shouldn't be in the module
          rm -f README.md CHANGELOG.md
          rm -rf .git .github

          # Create the module zip
          zip -r AlwaysTrustUserCerts.zip . -x "*.git*" ".DS_Store*"

          # Verify the structure
          echo "Module contents:"
          unzip -l AlwaysTrustUserCerts.zip

      - name: Upload Module
        uses: actions/upload-artifact@v4
        with:
          name: AlwaysTrustUserCerts
          path: AlwaysTrustUserCerts.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: AlwaysTrustUserCerts.zip
